app/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask import request, abort, jsonify, current_app
from flask_paginate import Pagination, get_page_args
from flask_login import login_user, logout_user, login_required, current_user
from app import db
from app.models import User, Course, Tag, Comment
# from app.models import favorites
from app.forms import LoginForm, RegistrationForm, CourseForm, EditUserForm
from app.forms import CreateCourseForm, CommentForm, ChangePasswordForm
from functools import wraps
from .kmp import kmp_search
from werkzeug.security import generate_password_hash, check_password_hash
import os

# get the relevant path
base_dir = os.path.abspath(os.path.dirname(__file__))

# set the path of the log file
user_log_file = os.path.join(base_dir, 'static/logs/user_logs.txt')
system_log_file = os.path.join(base_dir, 'static/logs/system_logs.txt')

main = Blueprint('main', __name__)


# log route
@main.route('/some_route')
def some_route():
    current_app.logger.info(f'{current_user.username} accessed some_route')
    current_app.logger.info('This is an informational log message.')
    current_app.logger.error('This is an error log message.')
    current_app.logger.warning('This is a warning log message.')
    return 'Some route'


# function to check if the user is a manager
def role_required(*required_roles):
    def decorator(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            current_app.logger.info(
                f'Checking role for user {current_user.username}')
            if not current_user.is_authenticated:
                current_app.logger.warning(
                    f'User {current_user.username} is not authenticated')
                abort(403)
            if current_user.role not in required_roles:
                current_app.logger.warning(
                    f'User {current_user.username} does not have '
                    f'required roles: {required_roles}')
                abort(403)
            return f(*args, **kwargs)
        return decorated_function
    return decorator

# the home page


@main.route('/')
def index():
    current_app.logger.info('Entering index')
    # the search query
    query = request.args.get('q', '')
    courses = Course.query.order_by(Course.created_at.desc()).limit(6).all()
    # if there is a search query
    if query:
        # search the courses
        matching_courses = []
        for course in courses:
            # use the KMP search algorithm
            if (kmp_search(course.title.lower(), query.lower()) or
                    kmp_search(course.description.lower(), query.lower())):
                matching_courses.append(course)
        return render_template('index.html', courses=matching_courses,
                               query=query)

    else:
        # get the latest 6 courses
        courses = Course.query.order_by(
            Course.created_at.desc()).limit(6).all()
    current_app.logger.info('Exiting index')
    return render_template('index.html', courses=courses, query=query)

# log page


@main.route('/logs')
@login_required
@role_required('manager')
def view_logs():
    # current_app.logger.info('Entering view_logs')
    page = request.args.get('page', 1, type=int)
    per_page = 20
    start_line = (page - 1) * per_page

    user_logs = ""
    system_logs = ""
    total_pages_user = 0
    total_pages_system = 0

    # print the use_log
    try:
        with open(user_log_file, 'r') as file:
            lines = file.readlines()
        if start_line >= len(lines):
            user_logs = "No more user logs available."
        else:
            user_logs = ''.join(lines[start_line:start_line + per_page])

        total_logs_user = len(lines)
        total_pages_user = (total_logs_user // per_page) + \
            (1 if total_logs_user % per_page > 0 else 0)

    except FileNotFoundError:
        user_logs = "No user log file found."

    # print the system log
    try:
        with open(system_log_file, 'r') as file:
            lines = file.readlines()
        if start_line >= len(lines):
            system_logs = "No more system logs available."
        else:
            system_logs = ''.join(lines[start_line:start_line + per_page])

        total_logs_system = len(lines)
        total_pages_system = (total_logs_system // per_page) + \
            (1 if total_logs_system % per_page > 0 else 0)

    except FileNotFoundError:
        system_logs = "No system log file found."

    total_pages = max(total_pages_user, total_pages_system)

    return render_template('log.html', user_logs=user_logs,
                           system_logs=system_logs, page=page,
                           total_pages=total_pages)


# login and register page
@main.route('/login', methods=['GET', 'POST'])
def login_register():
    current_app.logger.info('Entering login_register')
    if current_user.is_authenticated:
        current_app.logger.info(
            'User already authenticated, redirecting to index')
        return redirect(url_for('main.index'))

    login_form = LoginForm()
    register_form = RegistrationForm()

    if login_form.validate_on_submit() and 'login' in request.form:
        user = User.query.filter_by(username=login_form.username.data).first()
        # check if the user exists and the password is correct
        if user and user.check_password(login_form.password.data):
            login_user(user)
            current_app.logger.info(
                f'User {user.username} logged in successfully.')
            flash('Login successful!', 'success')
            next_page = request.args.get('next')
            current_app.logger.info('Exiting login_register')
            return redirect(next_page or url_for('main.index'))
        else:
            current_app.logger.warning(
                f'Failed login for username: {login_form.username.data}.')
            flash('Invalid username or password', 'danger')

    if register_form.validate_on_submit() and 'register' in request.form:
        # check if the username already exists
        user = User.query.filter_by(
            username=register_form.username.data).first()
        email = User.query.filter_by(email=register_form.email.data).first()
        if user:
            flash('Username already exists', 'danger')
        elif email:
            flash('Email already exists', 'danger')
        else:
            user = User(username=register_form.username.data,
                        email=register_form.email.data,
                        role=register_form.role.data)
            user.set_password(register_form.password.data)
            db.session.add(user)
            db.session.commit()
            current_app.logger.info(f'New user {user.username} registered.')
            flash('Registration successful! Please log in.', 'success')
            current_app.logger.info('Exiting login_register')
            return redirect(url_for('main.login_register'))
    else:
        if 'register' in request.form:
            flash('Registration failed. Please check errors.', 'danger')

    current_app.logger.info('Exiting login_register')
    return render_template('login.html', login_form=login_form,
                           register_form=register_form)


# change password
@main.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if not check_password_hash(current_user.password_hash,
                                   form.old_password.data):
            flash('Old password is incorrect', 'danger')
        else:
            current_user.password_hash = generate_password_hash(
                form.new_password.data)
            db.session.commit()
            flash('Your password has been updated!', 'success')
            return redirect(url_for('main.index'))
    return render_template('change_password.html', form=form)


# the logout function
@main.route('/logout')
@login_required
def logout():
    current_app.logger.info(f'User {current_user.username} logged out.')
    logout_user()
    return redirect(url_for('main.index'))


# the course page
@main.route('/courses')
def courses():
    current_app.logger.info('Entering courses')
    # get the selected tags from the query string
    tag_ids = request.args.getlist('tag')
    page = request.args.get('page', 1, type=int)

    # if tags are selected, filter courses by tags
    if tag_ids:
        tag_ids = [int(tag_id) for tag_id in tag_ids]
        # use 'any' method to filter courses that have any of the selected tags
        courses = Course.query.filter(Course.tags.any(
            Tag.id.in_(tag_ids))).paginate(page=page, per_page=9)
    else:
        courses = Course.query.paginate(page=page, per_page=9)

    tags = Tag.query.all()
    current_app.logger.info('Exiting courses')
    return render_template('courses.html',
                           courses=courses,
                           tags=tags,
                           selected_tags=tag_ids if tag_ids else [])


# the course detail page
@main.route('/course/<int:course_id>', methods=['GET', 'POST'])
def course_detail(course_id):
    current_app.logger.info(
        f'Entering course_detail for course_id: {course_id}')
    course = Course.query.get_or_404(course_id)
    form = CommentForm()
    page = request.args.get('page', 1, type=int)
    comments = Comment.query.filter_by(course_id=course_id).paginate(
        page=page, per_page=5, error_out=False)

    if form.validate_on_submit():
        if current_user.is_authenticated:
            comment = Comment(content=form.content.data,
                              user_id=current_user.id, course_id=course.id)
            db.session.add(comment)
            db.session.commit()
            flash('Your comment has been added.', 'success')
        else:
            flash('You need to be logged in to comment.', 'danger')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}base{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">

    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>

    <!-- jQuery CDN (remove any duplicate local jQuery file) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Bootstrap JS (use only one instance) -->
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <!-- Echarts -->
    <script src="https://cdn.jsdelivr.net/npm/echarts@5.3.3/dist/echarts.min.js"></script>
</head>


<body onload=getD1()>

    <!-- navigation -->
    <header class="p-3 mb-3 border-bottom fixed-top  ">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <div class="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis">
                    <i class="bi bi-mortarboard-fill logo" role="img"></i>
                </div>
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li>
                        <a class="nav-link active text-muted" aria-current="page"
                            href="{{ url_for('main.index') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <div class="vr d-none d-lg-flex h-100 mx-lg-2 text-white"></div>
                        <hr class="d-lg-none my-2 text-white-50">
                    </li>
                    <li><a class="nav-link px-2 link-body-emphasis" href="{{ url_for('main.courses') }}">Courses</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <!-- teacher or manager can create course -->
                    {% if current_user.role== "teacher" or current_user.role == "manager" %}

                    <li class="nav-item">
                        <div class="vr d-none d-lg-flex h-100 mx-lg-2 text-white"></div>
                        <hr class="d-lg-none my-2 text-white-50">
                    </li>
                    <li><a class="nav-link px-2 link-body-emphasis" href="{{ url_for('main.create_course') }}">Create
                            Course</a>
                    </li>
                    {% endif %}
                    {% if current_user.role== "manager" %}
                    <li class="nav-item">
                        <div class="vr d-none d-lg-flex h-100 mx-lg-2 text-white"></div>
                        <hr class="d-lg-none my-2 text-white-50">
                    </li>
                    <div class="dropdown d-flex align-items-center p-1 pe-2  nav-drop admin-nav">
                        <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Admin Dashboard
                        </a>
                        <ul class="dropdown-menu text-small drop-color">
                            <li><a class="dropdown-item" href="{{ url_for('main.user_record') }}">
                                    View user Information</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('main.course_record') }}">
                                    View Course</a></li>

                            <li><a class="dropdown-item" href="{{ url_for('main.view_logs') }}">
                                    Logs</a></li>

                        </ul>

                    </div>

                    {% endif %}
                    {% endif %}

                </ul>

                <div class="text-end d-flex ">

                    <!-- set the login state -->
                    {% if current_user.is_authenticated %}
                    <div
                        class="dropdown text-endbadge d-flex align-items-center p-1 pe-2 text-warning-emphasis bg-warning-subtle border border-warning-subtle rounded-pill nav-drop">
                        <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <img class="rounded-circle me-1" width="24" height="24"
                                src="{{url_for('static', filename= 'image/user.jpg')}}" alt="">Hello, {{
                            current_user.username
                            }}!
                        </a>
                        <ul class="dropdown-menu text-small drop-color">
                            <li><a class="dropdown-item" href="{{ url_for('main.my_courses') }}">My course</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{{ url_for('main.change_password') }}">
                                    Change Password</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{{ url_for('main.logout') }}">Logout</a></li>
                        </ul>
                    </div>
                    {% else %}
                    <a class="nav log-button" href="{{ url_for('main.login_register') }}">Login</a>
                    {% endif %}

                    <li class="nav-item">
                        <div class="vr d-none d-lg-flex h-100 mx-lg-2 text-white"></div>
                        <hr class="d-lg-none my-2 text-white-50">
                    </li>
                    <!-- read the website -->
                    <!-- the icon comes from bootsrtap -->
                    <div class=" text-end ">
                        <button id="readPage" class="btn btn-warning read-button">
                            <i id="speakerIcon" class="bi bi-volume-mute"></i>Speech
                        </button>
                    </div>
                </div>




            </div>
        </div>
    </header>



    <!-- Flash Message Section -->
    <div>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div id="flash-container">
            {% for category, message in messages %}
            <div class="flash-message alert alert-{{ category }}" role="alert">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
    </div>
    <!-- Cookie warning -->
    <div id="cookie-warning" class="cookie-warning">
        <p>We use cookies to enhance your browsing experience. By continuing to use this website, you agree to our
            Cookie
            Policy.</p>
        <button id="accept-cookie" class="btn btn-warning">Accept</button>
    </div>
    <!-- main body-->
    <div class="main-box main-color ">
        {% block content %}{% endblock %}
    </div>

    <!-- top bottom -->
    <!-- move top -->
    <button onclick="topFunction()" id="movetop" title="Go to top" class="top_bottom">
        <!-- the icon comes from bootstrap -->
        <i class="bi bi-arrow-up-circle-fill"></i>
    </button>

    <!-- icon comes from bootstrap -->
    <!-- definition of the button -->
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="facebook" viewBox="0 0 16 16">
            <path
                d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
        </symbol>
        <symbol id="instagram" viewBox="0 0 16 16">
            <path
                d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
        </symbol>
        <symbol id="twitter" viewBox="0 0 16 16">
            <path
                d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
        </symbol>
    </svg>


    <!-- footer  -->
    <div class="footer-colour theme-font">
        <div class="container ">
            <footer class="py-5">
                <div class="row ">
                    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                        <li class="nav-item"><a href="{{ url_for('main.index') }}"
                                class="nav-link px-2 text-body-secondary">Home</a></li>
                        <li class="nav-item"><a href="{{ url_for('main.courses') }}"
                                class="nav-link px-2 text-body-secondary">Courses</a></li>
                        <li class="nav-item"><a href="https://www.cac.gov.cn/2017-06/01/c_1121068451.htm"
                                class="nav-link px-2 text-body-secondary" target="_blank">License</a></li>
                    </ul>
                </div>

                <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 ">
                    <p>&copy; 2024 Henry. All rights reserved.</p>
                    <ul class="list-unstyled d-flex">
                        <li class="ms-3 "><a class="link-body-emphasis" href="https://x.com/?lang=zh"
                                aria-label="Twitter" target="_blank"><svg class="bi" width="24" height="24">
                                    <use xlink:href="#twitter" />
                                </svg></a></li>
                        <li class="ms-3"><a class="link-body-emphasis" href="https://www.instagram.com"
                                aria-label="Instagram" target="_blank"><svg class="bi" width="24" height="24">
                                    <use xlink:href="#instagram" />
                                </svg></a></li>
                        <li class="ms-3"><a class="link-body-emphasis"
                                href="https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F%3Flocale%3Dzh_CN"
                                aria-label="Facebook" target="_blank"><svg class="bi" width="24" height="24">
                                    <use xlink:href="#facebook" />
                                </svg></a></li>
                    </ul>
                </div>
            </footer>
        </div>
    </div>


    <!-- jQuery CDN -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Bootstrap JS -->
    <!-- CDN of Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+S49e1BoI1swpp3LrsEAmvU90PpF0"
        crossorigin="anonymous"></script>



    <!-- JS file -->
    <script src="{{ url_for('static', filename='js/top.js') }}"></script>
    <!-- <script src="{{ url_for('static', filename='js/login.js') }}"></script> -->
    <script src="{{ url_for('static', filename='js/flash.js') }}"></script>
    <script src="{{ url_for('static', filename='js/like.js') }}"></script>
    <!-- read the website -->
    <script src="{{ url_for('static', filename='js/readpage.js') }}"></script>
    <script src="{{ url_for('static', filename='js/validation.js') }}"></script>
    <script src="{{ url_for('static', filename='js/cookie.js') }}"></script>
</body>

</html>

app/templates/change_password.html
{% extends 'base.html' %}
{% block title %} Change Password {% endblock %}
{% block content %}
<div class="container">
    <div class="mt-3 search-tittle d-flex justify-content-center">
        <h1>Change Password</h1>
    </div>
    <form method="POST" class="change-box" action="{{ url_for('main.change_password') }}">
        {{ form.hidden_tag() }}
        <div class="form-group change-password">
            {{ form.old_password.label(class="form-label") }}
            {{ form.old_password(class="form-control") }}
            {% for error in form.old_password.errors %}
            <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group change-password">
            {{ form.new_password.label(class="form-label") }}
            {{ form.new_password(class="form-control") }}
            {% for error in form.new_password.errors %}
            <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group change-password">
            {{ form.confirm_password.label(class="form-label") }}
            {{ form.confirm_password(class="form-control") }}
            {% for error in form.confirm_password.errors %}
            <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group ">
            {{ form.submit(class="btn btn-warning changepass-button") }}
        </div>
    </form>
</div>
{% endblock %}

app/templates/courses.html
{% extends 'base.html' %}

{% block title %}courses{% endblock %}

{% block content %}
<div class="container">
    <div class="tag-filter-section course-filter">
        <h1>Course Tag</h1>
        <form id="tag-filter-form" method="get" action="{{ url_for('main.courses') }}">
            <div class="tag-checkbox-container tag-filter-box">
                {% for tag in tags %}
                <fieldset>
                    <legend>📖 🏷️</legend>
                    <div class="tag-checkbox tag-filter">
                        <input type="checkbox" name="tag" value="{{ tag.id }}" id="tag-{{ tag.id }}" {% if tag.id in
                            selected_tags %}checked{% endif %}>
                        <label for="tag-{{ tag.id }}">{{ tag.name }}</label>
                    </div>
                </fieldset>
                {% endfor %}
            </div>
            <div class="filter-submit">
                <button type="submit" class="btn btn-warning">Screening Courses</button>
            </div>
        </form>
    </div>
</div>
<!-- second section -->
<div class="album py-5 bg-body-tertiary">
    <div class="container">

        {% if courses.items %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for course in courses.items %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="course-media">
                        {% if course.image_url %}
                        <img src="{{ course.image_url }}" class="card-img-top" alt="{{ course.title }}">
                        {% elif course.video_url %}
                        <video class="card-img-top" controls>
                            <source src="{{ course.video_url }}" type="video/mp4">
                            Your browser does not support the video tag.
                        </video>
                        {% else %}
                        <svg class="bd-placeholder-img card-img-top" role="img" aria-label="Placeholder: Media"
                            preserveAspectRatio="xMidYMid slice" focusable="false">
                            <title>Placeholder</title>
                            <rect width="100%" height="100%" fill="#55595c" />
                            <text x="50%" y="50%" fill="#eceeef" dy=".3em">No media available</text>
                        </svg>
                        {% endif %}
                    </div>
                    <div class="card-body course-info">
                        <div class="card-title">{{ course.title }}</div>
                        <p class="card-text">{{ course.description }}</p>
                        <div class="course-tags">
                            {% for tag in course.tags %}
                            <span class="badge bg-secondary">{{ tag.name }}</span>
                            {% endfor %}
                        </div>
                        <div class="d-flex justify-content-between align-items-center mt-auto">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary course-button"><a
                                        href="{{ url_for('main.course_detail', course_id=course.id) }}"
                                        class="text-decoration-none ">Course details</a></button>
                            </div>
                            <small class="text-body-secondary">{{ course.created_at.strftime('%Y-%m-%d') }}</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        {% else %}
        <p>You have no courses yet.</p>
        {% endif %}
        <!-- Pagination -->
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if courses.has_prev %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('main.courses', page=courses.prev_num, tag=selected_tags) }}"
                        aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}
                {% for page_num in courses.iter_pages() %}
                <li class="page-item {% if page_num == courses.page %}active{% endif %}">
                    <a class="page-link" href="{{ url_for('main.courses', page=page_num, tag=selected_tags) }}">{{
                        page_num
                        }}</a>
                </li>
                {% endfor %}
                {% if courses.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('main.courses', page=courses.next_num, tag=selected_tags) }}"
                        aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>


{% endblock %}

app/templates/log.html
{% extends "base.html" %}
{% block title %}Manage the logs{% endblock %}
{% block content %}


<div class="log-box1">
    <h1>User Logs</h1>
    <pre>{{ user_logs }}</pre>

    <h1>System Logs</h1>
    <pre>{{ system_logs }}</pre>

    <div class="page-box1 ">
        {% if total_pages > 1 %}
        <div class="text-center">
            <ul class="pagination pagebox2">
                {% if page > 1 %}
                <li class="page-item1"><a href="{{ url_for('main.view_logs', page=page-1) }}">Previous</a></li>
                {% else %}
                <li class="disabled"><span>Previous</span></li>
                {% endif %}
                <span>&nbsp;&nbsp;</span>
                <li class="page-item1"><span>Page {{ page }} of {{ total_pages }}</span></li>
                <span>&nbsp;&nbsp;</span>
                {% if page < total_pages %} <li><a href="{{ url_for('main.view_logs', page=page+1) }}">Next</a></li>
                    {% else %}
                    <li class="disabled"><span>Next</span></li>
                    {% endif %}
            </ul>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}